// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufvdeelxuzvvahmkqjev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdmRlZWx4dXp2dmFobWtxamV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDQxNDUsImV4cCI6MjA1ODU4MDE0NX0.il_bKT8FNCmkc7U7aAGLZTOoqB0LpC8TbBgLa6X8J_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);